#!/usr/bin/env python3
"""Author raw PDM packing vectors, not target PCM converter samples.

The reference uses binary-string indexing and named slot routing, independently
of the implementation's bit shifts, counters, and register masks. Run with
--header PATH to author the C fixture consumed by esp32s3-i2s-pdm-test.c,
or with no arguments to emit JSON. No third-party modules or target hardware.
"""
import argparse
import json
from pathlib import Path


PDM = (1 << 20) | (1 << 12)  # raw data bypasses A-law/u-law conversion
MONO = 1 << 5
FIRST = 1 << 9
POL = 1 << 17
LSB = 1 << 18
BIG = 1 << 7
DAC = 1 << 24
DUAL = 1 << 23


def binary_unit(value, big_endian, lsb_first):
    octets = value.to_bytes(2, "little")
    text = "".join(f"{octet:08b}" for octet in reversed(octets))
    if big_endian:
        text = text[8:] + text[:8]
    return text[::-1] if lsb_first else text


def route(left, right, mode, polarity, single):
    return {
        0: (left, right),
        1: (right, right) if polarity else (left, left),
        2: (left, left) if polarity else (right, right),
        3: (left, single) if polarity else (single, right),
        4: (single, right) if polarity else (left, single),
    }[mode]


def author():
    cases = []
    for polarity in (False, True):
        for big in (False, True):
            for lsb in (False, True):
                for mono in (False, True):
                    for first_valid in ((False, True) if mono else (True,)):
                        for mode in range(5):
                            for line_mode in ("codec", "single-dac", "dual-dac"):
                                if line_mode == "single-dac" and not mono:
                                    continue
                                if line_mode == "dual-dac" and mono:
                                    continue
                                first, second, single = 0x1234, 0x56a9, 0x8bcd
                                a = binary_unit(first, big, lsb)
                                b = binary_unit(second, big, lsb)
                                constant = binary_unit(single, False, lsb)
                                if mono:
                                    left, right = (a, constant) if first_valid != polarity else (constant, a)
                                else:
                                    left, right = (b, a) if polarity else (a, b)
                                left, right = route(left, right, mode, polarity, constant)
                                if line_mode == "single-dac":
                                    left = right = a
                                edges = []
                                for left_bit, right_bit in zip(left, right):
                                    if line_mode == "codec":
                                        edges.extend((int(left_bit), int(right_bit)))
                                    elif line_mode == "single-dac":
                                        edges.extend((int(right_bit), int(right_bit)))
                                    else:
                                        both = int(right_bit) + 2 * int(left_bit)
                                        edges.extend((both, both))
                                cfg = PDM | (MONO if mono else 0) | (FIRST if first_valid else 0)
                                cfg |= POL if polarity else 0
                                cfg |= BIG if big else 0
                                cfg |= LSB if lsb else 0
                                cfg |= mode << 24
                                pdm_cfg = 0 if line_mode == "codec" else DAC
                                pdm_cfg |= DUAL if line_mode == "dual-dac" else 0
                                conf1 = ((15 if mono else 31) << 13) | (15 << 18)
                                cases.append(dict(cfg=cfg, conf1=conf1, pdm_cfg=pdm_cfg,
                                                  first=first, second=second, single=single,
                                                  line_mask=3 if line_mode == "dual-dac" else 1,
                                                  edges=edges))
    return cases


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--header", type=Path)
    args = parser.parse_args()
    cases = author()
    if args.header:
        declarations = [
            "/* Generated by pdm-reference-vectors.py; raw packing only. */",
            "static const struct PdmVector {",
            "    uint32_t cfg, conf1, pdm_cfg;",
            "    uint16_t first, second, single;",
            "    uint8_t line_mask, edges[32];",
            "} pdm_vectors[] = {",
        ]
        for case in cases:
            scalar_keys = ("cfg", "conf1", "pdm_cfg", "first", "second", "single", "line_mask")
            scalars = ", ".join(str(case[key]) for key in scalar_keys)
            edges = ", ".join(map(str, case["edges"]))
            declarations.append("    {" + scalars + ", {" + edges + "}},")
        declarations.extend(("};", ""))
        args.header.write_text("\n".join(declarations), encoding="utf-8")
    else:
        print(json.dumps({"kind": "raw-pdm-not-pcm-conversion", "vectors": cases}, indent=2))


if __name__ == "__main__":
    main()
